name: Check Build
on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - run: ./gradlew build --stacktrace --no-daemon
     
      - name: Publish Artifacts on GitHub Actions
        uses: actions/upload-artifact@v3   
        with:
          if-no-files-found: error
          path: build/libs/
          name: Vulkanite JAR

